export const dict = {
  ru: {
    nav: { today: "Сегодня", tasks: "Задачи", focus: "Фокус", projects: "Проекты", analytics: "Аналитика", settings: "Настройки", logout: "Выйти" },
    landing: { title: "Продуктивность\nбез хаоса", subtitle: "Задачи, фокус-сессии и привычки — всё в одном приложении. Без лишних кнопок.", cta: "Начать бесплатно", freeTitle: "Free", proTitle: "Pro", soon: "СКОРО", tasksTitle: "Задачи", tasksDesc: "Создавайте, фильтруйте и отслеживайте прогресс. MIT — главная задача дня.", focusTitle: "Фокус", focusDesc: "Pomodoro-таймер с тремя режимами. Сессии сохраняются в аналитику.", habitsTitle: "Привычки", habitsDesc: "Ежедневные привычки со стриками. Не прерывайте серию.", priceFree: "$0", pricePro: "$4", month: "/мес", freeProjects: "До 3 проектов", freeHabits: "До 5 привычек", freeTimer: "Базовый таймер", freeAnalytics: "Аналитика 7 дней", proProjects: "Неограниченные проекты", proHabits: "Неограниченные привычки", proAi: "AI-планирование дня", proExport: "Экспорт CSV", footer: "© 2026 TimeSync. Сделано с фокусом." },
    dashboard: { greeting_morning: "Доброе утро", greeting_day: "Добрый день", greeting_evening: "Добрый вечер", done: "Выполнено", focus: "Фокус", streak: "Streak", inProgress: "В работе", mit: "MIT", chooseMIT: "Выберите MIT", markDone: "Отметить выполненной", noTasks: "Нет задач на сегодня", meetings: "Встречи", noMeetings: "Нет встреч на сегодня", habits: "Привычки", noHabits: "Нет привычек. Добавьте первую!", add: "Добавить", newMeeting: "Новая встреча", newHabit: "Новая привычка", meetingName: "Название", start: "Начало", end: "Конец", habitName: "Название привычки", create: "Создать" },
    tasks: { title: "Задачи", add: "Добавить задачу", all: "Все", today: "Сегодня", upcoming: "Предстоящие", completed: "Завершённые", mit: "MIT", noTasks: "Нет задач", priority: "Приоритет", project: "Проект", dueDate: "Срок", cancel: "Отмена", save: "Сохранить", edit: "Редактировать задачу", delete: "Удалить", newTask: "Новая задача" },
    focus: { work: "РАБОТА", break: "ПЕРЕРЫВ", longBreak: "ДЛИННЫЙ ПЕРЕРЫВ", sessions: "сессий", timerStarted: "Таймер запущен", timerPaused: "Таймер на паузе", timerReset: "Таймер сброшен", currentTask: "Текущая задача", noActiveTasks: "Нет активных задач", chooseTask: "Выберите задачу...", sessionDone: "Сессия завершена! Отдыхайте.", breakDone: "Перерыв окончен! За работу." },
    analytics: { title: "Аналитика", completion: "Выполнение", focusTotal: "Фокус (всего)", habitsDone: "Привычки", habitsSub: "выполнено сегодня", maxStreak: "Стрик", maxStreakSub: "макс. серия", taskChart: "Выполнение задач", focusChart: "Часы фокуса", days7: "7 дней", priorities: "Приоритеты (активные)", daysInRow: "Дней подряд", keepItUp: "Продолжайте в том же духе!", habitTracker: "Трекер привычек", noHabits: "Нет привычек" },
    settings: { title: "Настройки", appearance: "Внешний вид", theme: "Тема", system: "Система", light: "Светлая", dark: "Тёмная", timer: "Помодоро таймер", mode: "Режим", soundVibro: "Звук и вибрация", sound: "Звук таймера", soundDesc: "Звуковой сигнал по завершении", vibration: "Вибрация", vibroDesc: "Вибросигнал по завершении", notifications: "Уведомления", timerNotif: "Конец таймера", timerNotifDesc: "Уведомление по завершении сессии", morning: "Утренний дайджест", morningDesc: "Напоминание о задачах на день", habits: "Привычки", habitsDesc: "Напоминание отметить привычки", tasks: "Задачи", showCompleted: "Показывать выполненные", showCompletedDesc: "Отображать завершённые задачи в списке", about: "О приложении", version: "Версия", privacy: "Политика конфиденциальности", terms: "Условия использования", reset: "Сбросить настройки", resetDesc: "Вернуть стандартные значения", resetConfirm: "Сбросить все настройки?", language: "Язык", langRu: "Русский", langEn: "English" },
    auth: { login: "Войти", register: "Создать аккаунт", email: "Email", password: "Пароль", name: "Имя", submitLogin: "Войти", submitRegister: "Создать аккаунт", loading: "Загрузка...", noAccount: "Нет аккаунта? Зарегистрироваться", haveAccount: "Уже есть аккаунт? Войти", tagline: "Продуктивность и фокус", error: "Ошибка регистрации" },
    common: { cancel: "Отмена", save: "Сохранить", delete: "Удалить", edit: "Редактировать", close: "Закрыть" }
  },
  en: {
    nav: { today: "Today", tasks: "Tasks", focus: "Focus", projects: "Projects", analytics: "Analytics", settings: "Settings", logout: "Log out" },
    landing: { title: "Productivity\nwithout chaos", subtitle: "Tasks, focus sessions and habits — all in one app. No extra buttons.", cta: "Start for free", freeTitle: "Free", proTitle: "Pro", soon: "SOON", tasksTitle: "Tasks", tasksDesc: "Create, filter and track progress. MIT — the most important task of the day.", focusTitle: "Focus", focusDesc: "Pomodoro timer with three modes. Sessions are saved to analytics.", habitsTitle: "Habits", habitsDesc: "Daily habits with streaks. Don't break the chain.", priceFree: "$0", pricePro: "$4", month: "/mo", freeProjects: "Up to 3 projects", freeHabits: "Up to 5 habits", freeTimer: "Basic timer", freeAnalytics: "7-day analytics", proProjects: "Unlimited projects", proHabits: "Unlimited habits", proAi: "AI day planning", proExport: "CSV export", footer: "© 2026 TimeSync. Made with focus." },
    dashboard: { greeting_morning: "Good morning", greeting_day: "Good afternoon", greeting_evening: "Good evening", done: "Done", focus: "Focus", streak: "Streak", inProgress: "In progress", mit: "MIT", chooseMIT: "Choose MIT", markDone: "Mark as done", noTasks: "No tasks for today", meetings: "Meetings", noMeetings: "No meetings for today", habits: "Habits", noHabits: "No habits. Add your first one!", add: "Add", newMeeting: "New meeting", newHabit: "New habit", meetingName: "Title", start: "Start", end: "End", habitName: "Habit name", create: "Create" },
    tasks: { title: "Tasks", add: "Add task", all: "All", today: "Today", upcoming: "Upcoming", completed: "Completed", mit: "MIT", noTasks: "No tasks", priority: "Priority", project: "Project", dueDate: "Due date", cancel: "Cancel", save: "Save", edit: "Edit task", delete: "Delete", newTask: "New task" },
    focus: { work: "WORK", break: "BREAK", longBreak: "LONG BREAK", sessions: "sessions", timerStarted: "Timer started", timerPaused: "Timer paused", timerReset: "Timer reset", currentTask: "Current task", noActiveTasks: "No active tasks", chooseTask: "Choose a task...", sessionDone: "Session complete! Take a break.", breakDone: "Break over! Back to work." },
    analytics: { title: "Analytics", completion: "Completion", focusTotal: "Focus (total)", habitsDone: "Habits", habitsSub: "done today", maxStreak: "Streak", maxStreakSub: "max series", taskChart: "Task completion", focusChart: "Focus hours", days7: "7 days", priorities: "Priorities (active)", daysInRow: "Days in a row", keepItUp: "Keep it up!", habitTracker: "Habit tracker", noHabits: "No habits" },
    settings: { title: "Settings", appearance: "Appearance", theme: "Theme", system: "System", light: "Light", dark: "Dark", timer: "Pomodoro timer", mode: "Mode", soundVibro: "Sound & vibration", sound: "Timer sound", soundDesc: "Sound signal on finish", vibration: "Vibration", vibroDesc: "Vibration on finish", notifications: "Notifications", timerNotif: "Timer end", timerNotifDesc: "Notification when session ends", morning: "Morning digest", morningDesc: "Reminder of tasks for the day", habits: "Habits", habitsDesc: "Reminder to check habits", tasks: "Tasks", showCompleted: "Show completed", showCompletedDesc: "Show completed tasks in list", about: "About", version: "Version", privacy: "Privacy Policy", terms: "Terms of Use", reset: "Reset settings", resetDesc: "Restore defaults", resetConfirm: "Reset all settings?", language: "Language", langRu: "Русский", langEn: "English" },
    auth: { login: "Log in", register: "Create account", email: "Email", password: "Password", name: "Name", submitLogin: "Log in", submitRegister: "Create account", loading: "Loading...", noAccount: "No account? Sign up", haveAccount: "Already have an account? Log in", tagline: "Productivity and focus", error: "Registration error" },
    common: { cancel: "Cancel", save: "Save", delete: "Delete", edit: "Edit", close: "Close" }
  }
} as const;

export type Lang = "ru" | "en";
export type Dict = typeof dict.ru;
